# Generated by Django 3.1 on 2020-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendgroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
