# Generated by Django 3.1 on 2020-08-24 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friendgroups', '0004_meeting_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='joined_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 8, 24, 20, 43, 23, 966884)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='friendgroups.group'),
        ),
    ]
