# Generated by Django 3.1 on 2020-08-31 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendgroups', '0005_auto_20200824_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
    ]
