# Generated by Django 3.1 on 2020-09-01 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friendgroups', '0006_remove_attendance_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='active_since',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='inactive_since',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
